// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaSzW-rOl1jzjE1BfXf6lFakTzCRU7uVs',
    appId: '1:903532749411:web:216cb93411aa9b5cdc0e56',
    messagingSenderId: '903532749411',
    projectId: 'chat-app-2-8f521',
    authDomain: 'chat-app-2-8f521.firebaseapp.com',
    storageBucket: 'chat-app-2-8f521.appspot.com',
    measurementId: 'G-VBV11SZ54N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoC0MKHbBW3G1ZEgB_q08A1Hx0fQml1-E',
    appId: '1:903532749411:android:280b19ec8431ece2dc0e56',
    messagingSenderId: '903532749411',
    projectId: 'chat-app-2-8f521',
    storageBucket: 'chat-app-2-8f521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKe0-zLqqhTgE7xQ8rrNIO18Fkcvc3R80',
    appId: '1:903532749411:ios:00db10c94bc11fd2dc0e56',
    messagingSenderId: '903532749411',
    projectId: 'chat-app-2-8f521',
    storageBucket: 'chat-app-2-8f521.appspot.com',
    iosClientId: '903532749411-rvnke9cle6mu18uao36b44ehmn38uv43.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKe0-zLqqhTgE7xQ8rrNIO18Fkcvc3R80',
    appId: '1:903532749411:ios:e6939781a04daadbdc0e56',
    messagingSenderId: '903532749411',
    projectId: 'chat-app-2-8f521',
    storageBucket: 'chat-app-2-8f521.appspot.com',
    iosClientId: '903532749411-r1l2a1od1euf26g4tr2n9qfd6fcqttth.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
